services:
  code:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: joi-to-zod-codemod-code
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
