name: Release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Use Node 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org

      - name: Bootstrap
        run: just bootstrap-ci

      - name: Publish ${{ github.ref_name }}
        run: just publish
        env:
          VERSION: ${{ github.ref_name }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
